# This is a basic workflow to help you get started with Actions

name: CI  

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
  
  schedule:
    - cron: "0 0 * * */4"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Run index.js
        env:
          KEY: ${{ secrets.KEY }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          cd actions
          npm i
          node .
          echo "Yoinked resume from Google Drive"
      - name: Print info
        run: |
          pwd
          ls
          cd ..
          pwd
          ls
      - uses: EndBug/add-and-commit@v9.1.0
        with:
          commit: --signoff
          message: "Auto yoink resume from Google Drive"
      
